### PR TITLE
Add single file support

### PR DESCRIPTION
**Pull request by lecorguille**
First modifications to allow one single unzip file.

Next steps:
1. Add the .CDF format support to use the faahKO test dataset
2. Create a merge tool using c(xset1, xset2, ...) as @sneumann proposed
3. ...

But one tricky part will be to pass functionnal tests. Because, we could provide zip file as option for retcor, fillpeaks and annote but how to provide individual files without transform the user interface?

### CODE REVIEW

**Comment by lecorguille** [comment]
- [x] Add the .CDF format support to use the faahKO test dataset
- [x] Create a merge tool using c(xset1, xset2, ...) as @sneumann proposed

**Comment by lecorguille** [comment]
This PR is stuck until this issue is not fixed https://github.com/galaxyproject/planemo/issues/604

**Comment by sneumann** [comment]
Hi, we'd like to start trying this out, is there any way to circumvent around the planemo issue ?

**Comment by lecorguille** [comment]
@sneumann 
The conda issues are now fixed. It is really new (last )

To do this, some new features within Galaxy was necessary:
 - Using Conda itself to merge the dependencies (why it was not this way ... I don't know)
 - Using the last version of Conda and Miniconda

This PR is my new priority.
Thanks for the UP

**Comment by lecorguille** [comment]
@sneumann You can test this new dev version from the testtoolshed: https://testtoolshed.g2.bx.psu.edu/repository?repository_id=4de78bc6e2ea0996&changeset_revision=3ed37f7df808
I will update a dev version of the docker container ASAP (next week, I hope ... we have some network issues in the lab)

**Pull request merged**
