### PR TITLE
XCMS 3.0.0 - Legacy mode: w/out any real changes

### PR DESCRIPTION
**Pull request by lecorguille**
Main thread: https://github.com/workflow4metabolomics/xcms/issues/77
- [ ] Legacy mode: try to just update XCMS without any real changes (fonctions, features ...)

### CODE REVIEW

**Comment by lecorguille** [comment]
@workflow4metabolomics/ms 

I'm wondering if it's normal that during `group` from xcms `3.0.0`, the number of Peaks Group is higher then when I use the `1.46.0`?

`1.46.0` -> Peak Groups: 8275
`3.0.0` -> Peak Groups: 8372

I can easily see that indeed, `3.0.0` doesn't group some peaks where `1.46.0` did so:
`1.46.0`
```
M598T3724	NA	29323.4050000004	NA	48876.8056363635
M595T3775	127545.669125001	NA	149919.4475625	NA
```
`3.0.0`
```
M598T3719	NA	NA	NA	48876.8056363635
M598T3730	NA	29323.4050000004	NA	NA
M595T3775	NA	NA	149919.4475625	NA
M595T3791	127545.669125001	NA	NA	NA
```

The other steps produce the same result as far I can see.
Are there some chances around `group`?

**Comment by lecorguille** [comment]
Yes, according to `?group`
And by the way, I set to in my tests so I'm not using the default value.

**Comment by jfrancoismartin** [comment]
Was it in the first group ? or after retention correction ?
There are a lot of modifications and bugs fixes in the 3.0 
https://rdrr.io/bioc/xcms/f/vignettes/new_functionality.Rmd
and I'm not suprised that these could affect the number of detected groups 
No?

**Comment by lecorguille** [comment]
Both!
In my `group` tests, I have data from `xcmsSet` and from `retcor`

**Comment by melpetera** [comment]
(I know, this PR is already merged)

I am still in an early step of thumbing through the docs but can the grouping difference come from this update?

```
CHANGES IN VERSION 1.53.1
--------------------------

BUG FIXES:
- Increase parameter n for the density call in the peak density correspondence
  method. This enables to separate neighboring peaks using small n (issue #161).
  Thanks to Jan Stanstrup.
```

**Pull request merged**
